-- MySQL Script generated by MySQL Workbench
-- Wed Apr  5 15:02:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema caos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema caos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `caos` DEFAULT CHARACTER SET utf8 ;
USE `caos` ;

-- -----------------------------------------------------
-- Table `caos`.`theme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caos`.`theme` ;

CREATE TABLE IF NOT EXISTS `caos`.`theme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `background` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caos`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caos`.`question` ;

CREATE TABLE IF NOT EXISTS `caos`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` TEXT NOT NULL,
  `theme_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `theme_id_idx` (`theme_id` ASC) VISIBLE,
  CONSTRAINT `theme_id`
    FOREIGN KEY (`theme_id`)
    REFERENCES `caos`.`theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caos`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caos`.`answer` ;

CREATE TABLE IF NOT EXISTS `caos`.`answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `question_id` INT NOT NULL,
  `isCorrect` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `question_id_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `caos`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
